import Foundation

/// `remote-config-gen.yml` の内容を表す設定。`input`と`outputs`以外は全てdefault値を持つ。
public struct GeneratorConfig: Equatable, Sendable {
    /// Remote Configテンプレートexport JSONへの、config基準の相対パス。
    public var input: String
    /// 生成する出力の一覧。空なら何も生成しない。
    public var outputs: [OutputConfig]
    /// 生成コードのアクセス修飾子。
    public var accessLevel: AccessLevel
    /// 各生成ファイルの先頭に付けるヘッダーコメント。
    public var headerComment: String
    /// `true`ならconditionalValuesの要約をdoc commentへ含める。
    public var includeConditionSummary: Bool
    /// `valueType`が`UNSPECIFIED`または未指定の場合に採用するSwift型。
    public var unspecifiedValueType: FallbackType

    public init(
        input: String,
        outputs: [OutputConfig] = [],
        accessLevel: AccessLevel = .public,
        headerComment: String = "Auto-generated by RemoteConfigGen. Do not edit.",
        includeConditionSummary: Bool = true,
        unspecifiedValueType: FallbackType = .string,
    ) {
        self.input = input
        self.outputs = outputs
        self.accessLevel = accessLevel
        self.headerComment = headerComment
        self.includeConditionSummary = includeConditionSummary
        self.unspecifiedValueType = unspecifiedValueType
    }
}

public extension GeneratorConfig {
    /// 生成コードのアクセス修飾子。
    enum AccessLevel: String, Equatable, Sendable {
        case `public`
        case package
        case `internal`
    }

    /// 型不明時のフォールバック先。
    enum FallbackType: String, Equatable, Sendable {
        case string
    }

    /// `outputs`の1エントリ。`type`によって`enum`（BOOLEAN parameter向け）か
    /// `keys`（BOOLEAN以外のparameter向け）かが決まる。
    enum OutputConfig: Equatable, Sendable {
        case enumOutput(EnumOutput)
        case keysOutput(KeysOutput)
    }

    /// BOOLEAN parameterをSwift enumとして出力する設定。
    struct EnumOutput: Equatable, Sendable {
        /// 生成するenum名。
        public var name: String
        /// 生成対象のkeyを絞り込み、かつcase名生成時に取り除く接頭辞。`nil`なら全BOOLEAN
        /// parameterが対象で、case名もkeyそのまま。raw value（元のkey文字列）には影響しない。
        public var keyPrefix: String?
        /// Remote Configテンプレートに存在しないが、生成対象に含めたいkeyの一覧（完全なkey文字列）。
        /// `keyPrefix`によるフィルタ・接頭辞除去は`additionalKeys`にも同様に適用される。
        /// テンプレート側に同名keyが既に存在する場合はエラーになる。
        public var additionalKeys: [String]
        /// 出力先ファイルパス（config基準の相対パス）。
        public var path: String
        /// `true`ならString raw valueでparameter key名を保持する。
        public var rawValue: Bool
        /// enumへ付与するprotocol conformance一覧。
        public var conformances: [String]

        public init(
            name: String,
            keyPrefix: String? = nil,
            additionalKeys: [String] = [],
            path: String,
            rawValue: Bool = true,
            conformances: [String] = ["CaseIterable", "Sendable"],
        ) {
            self.name = name
            self.keyPrefix = keyPrefix
            self.additionalKeys = additionalKeys
            self.path = path
            self.rawValue = rawValue
            self.conformances = conformances
        }
    }

    /// BOOLEAN以外のparameterを`static let`として出力する設定。
    struct KeysOutput: Equatable, Sendable {
        /// 生成するnamespace（enum）名。
        public var namespace: String
        /// 各keyをラップする型の名前（例: `RemoteConfigKey`）。
        public var keyType: String
        /// 出力先ファイルパス（config基準の相対パス）。
        public var path: String

        public init(
            namespace: String = "RemoteConfigKeys",
            keyType: String = "RemoteConfigKey",
            path: String,
        ) {
            self.namespace = namespace
            self.keyType = keyType
            self.path = path
        }
    }
}

public extension GeneratorConfig.AccessLevel {
    /// 宣言の先頭に置く文字列。`internal`は明示不要なので空文字（末尾スペース無し）。
    var declarationPrefix: String {
        switch self {
        case .public: "public "
        case .package: "package "
        case .internal: ""
        }
    }
}
