import Foundation

/// `config.yml` の内容を表す設定。`input`/`output.directory` 以外は全てdefault値を持つ。
public struct GeneratorConfig: Equatable, Sendable {
    /// 入力（remoteconfig.jsonのパス）。必須。
    public var input: Input
    /// 出力先ディレクトリ・アクセスレベル等の共通出力設定。
    public var output: Output
    /// key命名変換規則。
    public var naming: Naming
    /// Bool parameterのenum出力設定。
    public var boolOutput: BoolOutput
    /// Bool以外のparameterのstatic let出力設定。
    public var nonBoolOutput: NonBoolOutput
    /// 型不明時のフォールバック設定。
    public var typeFallback: TypeFallback
    /// condition要約のdoc comment焼き込み設定。
    public var documentation: Documentation

    public init(
        input: Input,
        output: Output,
        naming: Naming = Naming(),
        boolOutput: BoolOutput = BoolOutput(),
        nonBoolOutput: NonBoolOutput = NonBoolOutput(),
        typeFallback: TypeFallback = TypeFallback(),
        documentation: Documentation = Documentation(),
    ) {
        self.input = input
        self.output = output
        self.naming = naming
        self.boolOutput = boolOutput
        self.nonBoolOutput = nonBoolOutput
        self.typeFallback = typeFallback
        self.documentation = documentation
    }
}

public extension GeneratorConfig {
    /// 必須項目。`remote_config_json` の1項目のみ持つ。
    struct Input: Equatable, Sendable {
        /// Remote Configテンプレートexport JSONへの、config.yml基準の相対パス。
        public var remoteConfigJSON: String

        public init(remoteConfigJSON: String) {
            self.remoteConfigJSON = remoteConfigJSON
        }
    }

    /// 必須項目。`directory` の1項目のみ持つ（プロジェクトのSPM target構造に直結するためdefaultを置かない）。
    struct Output: Equatable, Sendable {
        /// 生成コードの出力先ディレクトリ。config.yml基準の相対パス。
        public var directory: String
        /// 生成コードのアクセスレベル。
        public var accessLevel: AccessLevel
        /// 各生成ファイルの先頭に付けるヘッダーコメント。
        public var headerComment: String

        public init(
            directory: String,
            accessLevel: AccessLevel = .public,
            headerComment: String = "Auto-generated by RemoteConfigGen. Do not edit.",
        ) {
            self.directory = directory
            self.accessLevel = accessLevel
            self.headerComment = headerComment
        }
    }

    /// 生成コードのアクセス修飾子。
    enum AccessLevel: String, Equatable, Sendable {
        case `public`
        case package
        case `internal`
    }

    /// key命名変換規則の設定。
    struct Naming: Equatable, Sendable {
        /// snake_caseのparameter keyをSwift識別子へ変換する規則。
        public var caseConvention: CaseConvention

        public init(caseConvention: CaseConvention = .camelCase) {
            self.caseConvention = caseConvention
        }
    }

    /// key命名変換規則。
    enum CaseConvention: String, Equatable, Sendable {
        case camelCase
    }

    /// Bool parameterをenumとして出力する際の設定。
    struct BoolOutput: Equatable, Sendable {
        /// `false`ならBool parameterのenum出力を丸ごとスキップする（既存の手書き型と衝突する等の理由で
        /// 生成不要な場合に使う）。
        public var enabled: Bool
        /// 出力ファイル名。`nil`なら `<enumName>.swift` を使う（`resolvedFileName`参照）。
        public var fileName: String?
        /// 生成するenum名。
        public var enumName: String
        /// `true`ならString raw valueでparameter key名を保持する。
        public var rawValue: Bool
        /// enumへ付与するprotocol conformance一覧。
        public var conformances: [String]
        /// case名生成時にkeyから取り除く接頭辞。raw value（元のkey文字列）には影響しない。
        /// 例: `"feature_flag_"`を指定すると、key `feature_flag_goalsApiWrite` の
        /// case名は`goalsApiWrite`になる（raw valueは元のkeyのまま）。
        public var stripKeyPrefix: String?
        /// 指定された場合、この接頭辞を持つBool parameterのみを生成対象にする。
        /// `nil`なら全Bool parameterが対象（従来通り）。`additionalKeys`はこのフィルタの影響を受けない。
        public var includeKeyPrefix: String?
        /// Remote Configテンプレートに存在しないが、生成対象に含めたいkeyの一覧（完全なkey文字列）。
        /// `stripKeyPrefix`は適用されるが`includeKeyPrefix`によるフィルタは適用されない。
        /// テンプレート側に同名keyが既に存在する場合はエラーになる（フラグがRemote Configへ
        /// 移行済みなのにconfig.ymlが更新されていないサイン）。
        public var additionalKeys: [String]

        public init(
            enabled: Bool = true,
            fileName: String? = nil,
            enumName: String = "FeatureFlag",
            rawValue: Bool = true,
            conformances: [String] = ["CaseIterable", "Sendable"],
            stripKeyPrefix: String? = nil,
            includeKeyPrefix: String? = nil,
            additionalKeys: [String] = [],
        ) {
            self.enabled = enabled
            self.fileName = fileName
            self.enumName = enumName
            self.rawValue = rawValue
            self.conformances = conformances
            self.stripKeyPrefix = stripKeyPrefix
            self.includeKeyPrefix = includeKeyPrefix
            self.additionalKeys = additionalKeys
        }

        /// 実際に使う出力ファイル名。`fileName`が未指定なら`enumName`から導出する。
        public var resolvedFileName: String {
            fileName ?? "\(enumName).swift"
        }
    }

    /// Bool以外のparameterをstatic letとして出力する際の設定。
    struct NonBoolOutput: Equatable, Sendable {
        /// `false`なら非Bool parameterのstatic let出力を丸ごとスキップする（既存の手書き型と衝突する等の
        /// 理由で生成不要な場合に使う）。
        public var enabled: Bool
        /// 出力ファイル名。`nil`なら `<namespace>.swift` を使う（`resolvedFileName`参照）。
        public var fileName: String?
        /// 生成するnamespace（enum）名。
        public var namespace: String
        /// 各keyをラップする型の名前（例: `RemoteConfigKey`）。
        public var keyType: String

        public init(
            enabled: Bool = true,
            fileName: String? = nil,
            namespace: String = "RemoteConfigKeys",
            keyType: String = "RemoteConfigKey",
        ) {
            self.enabled = enabled
            self.fileName = fileName
            self.namespace = namespace
            self.keyType = keyType
        }

        /// 実際に使う出力ファイル名。`fileName`が未指定なら`namespace`から導出する。
        public var resolvedFileName: String {
            fileName ?? "\(namespace).swift"
        }
    }

    /// 型不明時のフォールバック設定。
    struct TypeFallback: Equatable, Sendable {
        /// `valueType`が`UNSPECIFIED`または未指定の場合に採用するSwift型。
        public var unspecifiedValueType: FallbackType

        public init(unspecifiedValueType: FallbackType = .string) {
            self.unspecifiedValueType = unspecifiedValueType
        }
    }

    /// 型不明時のフォールバック先。
    enum FallbackType: String, Equatable, Sendable {
        case string
    }

    /// condition要約のdoc comment焼き込み設定。
    struct Documentation: Equatable, Sendable {
        /// `true`ならconditionalValuesの要約をdoc commentへ含める。
        public var includeConditionSummary: Bool

        public init(includeConditionSummary: Bool = true) {
            self.includeConditionSummary = includeConditionSummary
        }
    }
}
