/// `RemoteConfigKeys`と、その中へネストするkey enumのSwiftソースコードを組み立てる。
enum EnumSourceBuilder {
    struct Definition {
        let name: String
        let cases: [Case]
    }

    struct Case {
        let name: String
        let rawValue: String
    }

    static func build(defaults: [Definition], additionalNamespaces: [Definition]) -> String {
        var lines = [
            "// Auto-generated by RemoteConfigGen. Do not edit.",
            "",
            "public enum RemoteConfigKeys {",
        ]

        append(definitions: defaults, to: &lines)
        append(definitions: additionalNamespaces, to: &lines)

        lines.append("}")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func append(definitions: [Definition], to lines: inout [String]) {
        for definition in definitions {
            lines.append("    public enum \(definition.name): String, CaseIterable, Sendable {")
            for member in definition.cases {
                let escapedRawValue = member.rawValue
                    .replacingOccurrences(of: "\\", with: "\\\\")
                    .replacingOccurrences(of: "\"", with: "\\\"")
                if member.name == member.rawValue {
                    lines.append("        case \(member.name)")
                } else {
                    lines.append("        case \(member.name) = \"\(escapedRawValue)\"")
                }
            }
            lines.append("    }")
        }
    }
}
