@testable import RemoteConfigGenKit
import Testing

struct ConfigLoaderTests {
    private let loader = ConfigLoader()

    @Test("required fields only fills in every default")
    func minimalConfigUsesDefaults() throws {
        let config = try loader.parse(
            """
            input:
              remote_config_json: "firebase/remoteconfig.production.json"
            output:
              directory: "Sources/RemoteConfigKeys/Generated"
            """,
        )

        #expect(config.input.remoteConfigJSON == "firebase/remoteconfig.production.json")
        #expect(config.output.directory == "Sources/RemoteConfigKeys/Generated")
        #expect(config.output.accessLevel == .public)
        #expect(config.output.headerComment == "Auto-generated by RemoteConfigGen. Do not edit.")
        #expect(config.naming.caseConvention == .camelCase)
        #expect(config.boolOutput.enumName == "FeatureFlag")
        #expect(config.boolOutput.fileName == nil)
        #expect(config.boolOutput.resolvedFileName == "FeatureFlag.swift")
        #expect(config.boolOutput.rawValue == true)
        #expect(config.boolOutput.conformances == ["CaseIterable", "Sendable"])
        #expect(config.boolOutput.stripKeyPrefix == nil)
        #expect(config.nonBoolOutput.namespace == "RemoteConfigKeys")
        #expect(config.nonBoolOutput.fileName == nil)
        #expect(config.nonBoolOutput.resolvedFileName == "RemoteConfigKeys.swift")
        #expect(config.nonBoolOutput.keyType == "RemoteConfigKey")
        #expect(config.typeFallback.unspecifiedValueType == .string)
        #expect(config.documentation.includeConditionSummary == true)
    }

    @Test("missing input.remote_config_json is an error")
    func missingInputIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                output:
                  directory: "Generated"
                """,
            )
        }
    }

    @Test("missing output.directory is an error")
    func missingOutputDirectoryIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input:
                  remote_config_json: "firebase/remoteconfig.production.json"
                """,
            )
        }
    }

    @Test("bool_output.enum_name without file_name derives the file name from it")
    func enumNameDerivesFileName() throws {
        let config = try loader.parse(
            """
            input:
              remote_config_json: "a.json"
            output:
              directory: "Generated"
            bool_output:
              enum_name: "Flags"
            """,
        )

        #expect(config.boolOutput.enumName == "Flags")
        #expect(config.boolOutput.fileName == nil)
        #expect(config.boolOutput.resolvedFileName == "Flags.swift")
    }

    @Test("explicit file_name overrides the derived name")
    func explicitFileNameOverridesDerivedName() throws {
        let config = try loader.parse(
            """
            input:
              remote_config_json: "a.json"
            output:
              directory: "Generated"
            bool_output:
              enum_name: "Flags"
              file_name: "CustomFlags.swift"
            """,
        )

        #expect(config.boolOutput.fileName == "CustomFlags.swift")
    }

    @Test("bool_output.strip_key_prefix is parsed")
    func parsesStripKeyPrefix() throws {
        let config = try loader.parse(
            """
            input:
              remote_config_json: "a.json"
            output:
              directory: "Generated"
            bool_output:
              strip_key_prefix: "feature_flag_"
            """,
        )

        #expect(config.boolOutput.stripKeyPrefix == "feature_flag_")
    }

    @Test("invalid access_level is an error")
    func invalidAccessLevelIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input:
                  remote_config_json: "a.json"
                output:
                  directory: "Generated"
                  access_level: "private"
                """,
            )
        }
    }

    @Test("full config overrides every default")
    func fullConfigOverridesDefaults() throws {
        let config = try loader.parse(
            """
            input:
              remote_config_json: "custom/path.json"
            output:
              directory: "Custom/Generated"
              access_level: "internal"
              header_comment: "Do not touch."
            naming:
              case_convention: "camelCase"
            bool_output:
              file_name: "Flags.swift"
              enum_name: "MyFlags"
              raw_value: false
              conformances: ["Sendable"]
            non_bool_output:
              file_name: "Keys.swift"
              namespace: "MyKeys"
              key_type: "MyKeyType"
            type_fallback:
              unspecified_value_type: "string"
            documentation:
              include_condition_summary: false
            """,
        )

        #expect(config.output.accessLevel == .internal)
        #expect(config.output.headerComment == "Do not touch.")
        #expect(config.boolOutput.rawValue == false)
        #expect(config.boolOutput.conformances == ["Sendable"])
        #expect(config.nonBoolOutput.namespace == "MyKeys")
        #expect(config.nonBoolOutput.keyType == "MyKeyType")
        #expect(config.documentation.includeConditionSummary == false)
    }
}
