@testable import RemoteConfigGenKit
import Testing

struct ConfigLoaderTests {
    private let loader = ConfigLoader()

    @Test("input-only config fills in every default and has no outputs")
    func minimalConfigUsesDefaults() throws {
        let config = try loader.parse(
            """
            input: "firebase/remoteconfig.production.json"
            """,
        )

        #expect(config.input == "firebase/remoteconfig.production.json")
        #expect(config.outputs.isEmpty)
        #expect(config.accessLevel == .public)
        #expect(config.headerComment == "Auto-generated by RemoteConfigGen. Do not edit.")
        #expect(config.includeConditionSummary == true)
        #expect(config.unspecifiedValueType == .string)
    }

    @Test("missing input is an error")
    func missingInputIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse("outputs: []")
        }
    }

    @Test("an outputs entry without a recognized type is an error")
    func unrecognizedOutputTypeIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input: "a.json"
                outputs:
                  - type: "bogus"
                    name: "Flags"
                    path: "Flags.swift"
                """,
            )
        }
    }

    @Test("an enum output requires name and path")
    func enumOutputRequiresNameAndPath() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input: "a.json"
                outputs:
                  - type: "enum"
                    path: "Flags.swift"
                """,
            )
        }
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input: "a.json"
                outputs:
                  - type: "enum"
                    name: "Flags"
                """,
            )
        }
    }

    @Test("a full enum output overrides every default")
    func fullEnumOutputOverridesDefaults() throws {
        let config = try loader.parse(
            """
            input: "custom/path.json"
            access_level: "internal"
            header_comment: "Do not touch."
            include_condition_summary: false
            unspecified_value_type: "string"
            outputs:
              - type: "enum"
                name: "FeatureFlag"
                key_prefix: "feature_flag_"
                additional_keys: ["feature_flag_mentorInvitation"]
                path: "Generated/FeatureFlag+Generated.swift"
                raw_value: false
                conformances: ["Sendable"]
            """,
        )

        #expect(config.accessLevel == .internal)
        #expect(config.headerComment == "Do not touch.")
        #expect(config.includeConditionSummary == false)
        #expect(config.outputs.count == 1)

        guard case let .enumOutput(enumOutput) = config.outputs[0] else {
            Issue.record("expected an enum output")
            return
        }
        #expect(enumOutput.name == "FeatureFlag")
        #expect(enumOutput.keyPrefix == "feature_flag_")
        #expect(enumOutput.additionalKeys == ["feature_flag_mentorInvitation"])
        #expect(enumOutput.path == "Generated/FeatureFlag+Generated.swift")
        #expect(enumOutput.rawValue == false)
        #expect(enumOutput.conformances == ["Sendable"])
    }

    @Test("a keys output requires path and defaults namespace/keyType")
    func keysOutputDefaultsNamespaceAndKeyType() throws {
        let config = try loader.parse(
            """
            input: "a.json"
            outputs:
              - type: "keys"
                path: "Generated/RemoteConfigKeys.swift"
            """,
        )

        guard case let .keysOutput(keysOutput) = config.outputs[0] else {
            Issue.record("expected a keys output")
            return
        }
        #expect(keysOutput.namespace == "RemoteConfigKeys")
        #expect(keysOutput.keyType == "RemoteConfigKey")
        #expect(keysOutput.path == "Generated/RemoteConfigKeys.swift")
    }

    @Test("multiple outputs of different types are parsed together")
    func multipleOutputsParsedTogether() throws {
        let config = try loader.parse(
            """
            input: "a.json"
            outputs:
              - type: "enum"
                name: "FeatureFlag"
                path: "FeatureFlag.swift"
              - type: "keys"
                path: "RemoteConfigKeys.swift"
            """,
        )

        #expect(config.outputs.count == 2)
    }

    @Test("invalid access_level is an error")
    func invalidAccessLevelIsError() {
        #expect(throws: RemoteConfigGenError.self) {
            try loader.parse(
                """
                input: "a.json"
                access_level: "private"
                """,
            )
        }
    }
}
